name: CI
on: ["push", "pull_request"]

jobs:
  test:
    name: Test contracts
    runs-on: ubuntu-latest
    env:
      REPORT_GAS: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Init submodules
        run: git submodule init

      - name: Update submodules
        run: git submodule update

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npm run compile

      - name: Run tests
        run: npm run test

      - name: Coverage
        run: npm run coverage
